# Generated by Django 3.2.22 on 2023-10-27 01:59

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('jacket', 'Jacket'), ('tops', 'Tops'), ('jean', 'Jean'), ('gown', 'Gown'), ('jogger', 'Jogger')], default='all', max_length=20)),
                ('type', models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='all', max_length=20)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=4)),
                ('size_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('color_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='product.product')),
            ],
        ),
    ]
