# Generated by Django 4.2.1 on 2023-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='product_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jacket', 'Jacket'), ('tops', 'Tops'), ('jean', 'Jean'), ('gown', 'Gown'), ('jogger', 'Jogger')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='all', max_length=20),
        ),
    ]
