# Generated by Django 4.2.1 on 2023-10-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_productimage_image_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='color_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsizes',
            name='size_product',
            field=models.ForeignKey(default=24778824, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(blank=True, related_name='images_product', to='product.productimage'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(blank=True, related_name='colors_product', to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(blank=True, related_name='sizes_product', to='product.productsizes'),
        ),
    ]
