# Generated by Django 4.2.1 on 2023-10-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcolor_color_product_productsizes_size_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color_product',
        ),
        migrations.RemoveField(
            model_name='productsizes',
            name='size_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(blank=True, to='product.productimage'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productsizes'),
        ),
    ]
