# Generated by Django 4.2.1 on 2023-10-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productcolor_color_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
