# Generated by Django 4.2.1 on 2023-10-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product'),
        ),
    ]
