# Generated by Django 4.2.1 on 2023-10-20 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productimage_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sizes',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsizes',
            name='size_product',
            field=models.ForeignKey(default=13131, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='product.product'),
            preserve_default=False,
        ),
    ]
